services:
  - type: web
    name: flask-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:flask_app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7651553668:AAFbL3yM27J67e3XKiU6O35pRQ_v0n5ZkX8
  # You can also set this directly via the Render dashboard
