services:
  - type: web
    name: flask-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:flask_app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8113582302:AAH6lIl3VlbeAsLUURyP9cBTW_yTqTXDNzk  # You can also set this directly via the Render dashboard
